name: pan_code_test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  dio: ^5.3.3
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  get_it: ^7.6.4
  shimmer: ^3.0.0
  get: ^4.6.6
  intl: ^0.19.0
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.8
  flutter_lints: ^3.0.0

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/font/raleway/Raleway-Heavy.ttf
        - asset: assets/font/raleway/Raleway-ExtraBold.ttf
        - asset: assets/font/raleway/Raleway-Bold.ttf
        - asset: assets/font/raleway/Raleway-SemiBold.ttf
        - asset: assets/font/raleway/Raleway-Thin.ttf
        - asset: assets/font/raleway/Raleway-Light.ttf
        - asset: assets/font/raleway/Raleway-ExtraLight.ttf
        - asset: assets/font/raleway/Raleway-Medium.ttf
        - asset: assets/font/raleway/Raleway-Regular.ttf
